[versions]
java = "17"

[libraries]
spring-boot-bom = "org.springframework.boot:spring-boot-dependencies:2.6.4"
jackson-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.3"
kotlin-logging = "io.github.microutils:kotlin-logging:2.1.21"

[bundles]
jackson = ["jackson-kotlin"]

[plugins]
kotlin-jvm = "org.jetbrains.kotlin.jvm:1.7.0"
gatling = "io.gatling.gradle:3.8.4"
