/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.adriferracuti.app

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
open class App

@Suppress("SpreadOperator")
fun main(args: Array<String>) {
    SpringApplication.run(App::class.java, *args)
}
